# theme: jekyll-theme-cayman
title: NUNU
description:      "Such theme, very cool."
url:              https://pnunu.github.io # Site url, without a slash at the end.
signoff:          "pnunu" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         首页
    url:          /
    external:     false
  - name:         关于我
    url:          /about
    external:     false
  - name:         关于我
    url:          /about
    external:     false



permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

owner: 
  name: "小小暮雨"
  email: bjnunu@163.com
  bio: ""
